### ISSUE TITLE
Code Missing

### ISSUE THREAD

**Issue by CodeBreaker444** [konskyrt/Concrete-Crack-Detection#2]
Hi,
  Can i get the full code because we are looking to analyse existing crack detection architecture? If you could provide me the webapp along with the weigths. Thank you

**Comment by rrryan2016** [comment]
How to get access to the web app mentioned in README? No feedback/output when run `main.py`

**Comment by konskyrt** [comment]
Hi there, the app is not yet opensourced

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
